version: '3'

services:

  rhies-client-registry-server:
    image: nextreflexe-api:latest
    container_name: nextreflexe-api
    ports:
      - "8090:3000"
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M

