version: '3'

services:

  rhies-client-registry-server:
    image: registry.gitlab.com/rbc5/metadata-management:latest
    container_name: matadata-management
    ports:
      - "8090:3000"
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M

